#!/bin/sh
case $0 in
	*mkdeck)
		decksh occupation.dsh | pdf -pagesize $portrait     -sans $duboisans -serif $duboiserif $* ;;
	*mkdeck-png)
		decksh occupation.dsh | pngdeck -pagesize $portrait -sans $duboisans -serif $duboiserif $* /dev/stdin ;;
esac
